# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target '15MDz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 15MDz
  pod 'SnapKit', '~> 5.0.0'

end
